name: remote_state
author: Ryan Edge <ryan.c.edge@outlook.com>
version: 0.11.0
homepage: https://github.com/chimon2000/remote_state
description: A new Flutter package project.
environment:
  sdk: '>=2.1.0 <3.0.0'
dependencies:
  freezed_annotation: ^0.7.1
dev_dependencies:
  build_runner: ^1.7.2
  freezed: ^0.10.6
  state_notifier: ^0.4.0
  test: ^1.12.0
  test_coverage: ^0.4.1
