name: remote_state
version: 0.16.0
homepage: https://github.com/chimon2000/remote_state
description: Tools for mapping data from remote sources in Dart, similar to Elm's RemoteData.
environment: 
  sdk: '>=2.1.0 <3.0.0'
dependencies: 
  freezed_annotation: ^0.7.1
dev_dependencies: 
  build_runner: ^1.7.2
  freezed: ^0.10.6
  state_notifier: ^0.4.0
  test: ^1.12.0
  test_coverage: ^0.4.1
