name: remote_state
description: A new Flutter package project.
version: 0.0.1
author: Ryan Edge <ryan.c.edge@outlook.com>
homepage: https://github.com/chimon2000/remote_state

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  freezed_annotation: ^0.7.1
  flutter:
    sdk: flutter

dev_dependencies:
  state_notifier: ^0.4.0
  flutter_state_notifier: ^0.4.1
  freezed: ^0.10.6
  build_runner: ^1.7.2
  flutter_test:
    sdk: flutter

flutter:
