name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest
    env:
      working-directory: ./packages/remote_state
    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pub get
      working-directory: ${{env.working-directory}}
    - name: Run tests
      run: pub run test
      working-directory: ${{env.working-directory}}
